apiVersion: v1
kind: Service
metadata:
  name: sample-web-service
spec:
  selector:
    app: sample-web
  ports:
    - protocol: TCP
      port: 80         # 서비스가 노출하는 포트
      targetPort: 80    # 포드(컨테이너) 내부 포트
      nodePort: 30080   # 외부에서 접속할 포트 (30000-32767 사이)
  type: NodePort
